from __future__ import annotations

from .core import RepoBrief
import json


def render_markdown(brief: RepoBrief) -> str:
    lines = [
        "# Agent Brief",
        "",
        f"Generated for `{brief.root_name}`.",
        "",
        "## Project Signals",
        "",
        _bullet("Languages", _join_or_none(brief.languages)),
        _bullet("Files scanned", str(brief.total_files_seen)),
        _bullet("Dependency files", _join_or_none(brief.dependency_files)),
        _bullet("Documentation", _join_or_none(brief.docs)),
        _bullet("CI", _join_or_none(brief.ci)),
        _bullet("Tests", _join_or_none(brief.tests)),
        "",
    ]

    if brief.package_scripts:
        lines.extend(["## Package Scripts", ""])
        lines.extend(f"- `{name}`: `{command}`" for name, command in brief.package_scripts.items())
        lines.append("")

    if brief.notable_files:
        lines.extend(["## Notable Files", ""])
        lines.extend(f"- `{path}`" for path in brief.notable_files)
        lines.append("")

    lines.extend(
        [
            "## Suggested Agent Instructions",
            "",
            "- Read dependency, test, and CI files before editing shared behavior.",
            "- Prefer existing project scripts over ad hoc commands.",
            "- Keep generated output, dependency directories, and build artifacts out of edits.",
            "- Add or update focused tests when changing behavior.",
            "- Preserve user changes already present in the working tree.",
            "",
            "<!-- Generated by AgentBrief. Edit this file to add project-specific human guidance. -->",
            "",
        ]
    )
    return "\n".join(lines)


def render_json(brief: RepoBrief) -> str:
    return json.dumps(brief.to_dict(), indent=2, sort_keys=True) + "\n"


def _bullet(label: str, value: str) -> str:
    return f"- {label}: {value}"


def _join_or_none(values: list[str]) -> str:
    return ", ".join(f"`{value}`" for value in values) if values else "none detected"

